name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: List directory contents
      run: ls -R

    - name: Make gradlew executable
      run: chmod +x ./app/gradlew

    - name: Build with Gradle
      run: cd app && ./gradlew build

    - name: Run tests with coverage
      run: cd app && ./gradlew test jacocoTestReport

    - name: Upload coverage to Code Climate
      run: |
        cd app
        ./gradlew jacocoTestReport
        bash <(curl -s https://codeclimate.com/test_reports) -r build/reports/jacoco/test/jacocoTestReport.xml
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}

    - name: Show test results
      if: failure()
      run: cd app && cat build/test-results/test/binary/TEST-hexlet.code.DifferTest.xml
